#!/usr/bin/env bash
# Cheack if there are less than 3 parameters
#	1. The path to the file to be transferred
#	2. The IP of the server we want to transfer the file to
#	3. The username scp connects with
#	4. The path to the SSH private key that scp uses

if [ "$#" -lt 3 ]
then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 3 ]
then
   scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
   scp -o StrictHostKeychecking=no -i "$4" "$1" "$3@$2:~/"
fi
