#!/usr/bin/env bash
# doing some very beneficial redirection on nginx web server

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/amyn00 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

service nginx restart
