#!/usr/bin/env bash

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    ./1-install_nginx_web_server
fi

# Create a new Nginx configuration file for redirection
echo "server {" > /etc/nginx/sites-available/redirect_me
echo "    listen 80;" >> /etc/nginx/sites-available/redirect_me
echo "    server_name _;" >> /etc/nginx/sites-available/redirect_me
echo "    location /redirect_me {" >> /etc/nginx/sites-available/redirect_me
echo "        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" >> /etc/nginx/sites-available/redirect_me
echo "    }" >> /etc/nginx/sites-available/redirect_me
echo "}" >> /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the new configuration
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration and reload
nginx -t && service nginx reload
