#!/usr/bin/env bash
# Customising 404 page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

# Creating a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listing 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart ngnix

service nginx restart
