#!/usr/bin/env bash
# doing some very beneficial redirection on nginx web server
# Customising 404 page

apt-get update
apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/amyn00 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listing 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart ngnix

service nginx restart
