#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.
# sleep 2 btn each iteration
# I am invincible!!! when receving a SIGTERM signal


while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
