#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,
# but for the 9th iteration, displays Best School and then Hi

cnt=0

while [ $cnt -lt 10 ]
do
	echo "Best School"
	((cnt++))
	if [ $cnt -eq 9 ]
	then
		echo "Hi"
	fi
done
