#!/usr/bin/env bash
# This script is displaying "Best School" 10 times,
# but for the 9th iteration, displays Best School and then Hi

cnt=0

while [ $cnt -lt 10 ]
do
	if [ $cnt -eq 3 ]
	then
		echo "bad luck"
	elif [ $cnt -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((cnt++))
done
