#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20

cnt=1

while [ $cnt -le 20 ]
do
	case $cnt in
		4)
			echo $cnt
			echo "bad luck from China"
			;;
		9)
			echo $cnt
			echo "bad luck from Japan"
			;;
		17)
			echo $cnt
			echo "bad luck from Italy"
			;;
		*)
			echo $cnt
			;;
	esac
	((cnt++))
done
