#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.

h=0
min=1

while [ $h -le 12 ]
do
	echo "Hour: $h"
	while [ $min -le 59 ]
	do
		echo $min
		((min++))
	done
	((h++))
	min=1
done
